# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfd56c10beb55080748317472b1b601f0bfdfbae1bbe29646b01dda56c331e082a0a0b7e54ee1c511352dec08453d0329a230fd203e2de1371bbca64de3ad555

test:
  secret_key_base: e13fdc9c98190ce090959b787873205a32221d9756adefff66cd50a30de934e1be7dc18e62825201b20364fbc91a82e2523676c49f9ec00c3ac4060179f9824e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
